# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e1cddd1697329896984b1bcfe58b639f9c5d630bb2659c4a9e5a8b3084881fcbc90f36f8b33afce69c765c3b7bce45eecbc7db6e5e2e250a0c8afeabc0cfcf2

test:
  secret_key_base: 156264de39dc033868dd60cc668124682cac3c1c221c94ccb5c52ad4a677e8480ddc926cc1422ed130eedfcba4d0720dba32a16d52547a4038df8425da31aa7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
   secret_key_base: 4fd542257858486c18a360cab107db4fc7caff13eecee1a228fe8fe6cb41f4e13743e0592dc96081ad8153def9b312f907b153fc60bfe4d51cb4aa7dca706d99
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
