---
- name: Install dependencies for rbenv
  apt: name={{ item }} state=latest
  with_items:
    - git

- name: Install rbenv
  become: yes
  become_user: "{{ rbenv_user }}"
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: Add ~/.rbenv/bin to $PATH
  become: yes
  become_user: "{{ rbenv_user }}"
  lineinfile: >
    dest="~/.profile"
    line="export PATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"

- name: Eval rbenv init in ~/.profile
  become: yes
  become_user: "{{ rbenv_user }}"
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)"'

- name: Install dependencies for ruby-build (see. https://github.com/sstephenson/ruby-build/wiki)
  apt: name={{ item }} state=latest
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: Install ruby-build as rbenv plugin
  become: yes
  become_user: "{{ rbenv_user }}"
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Check if version is installed ruby
  become: yes
  become_user: "{{ rbenv_user }}"
  shell: ". ~/.profile && rbenv versions | grep {{ rbenv_ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: yes

- name: Install ruby
  become: yes
  become_user: "{{ rbenv_user }}"
  shell: ". ~/.profile && rbenv install {{ rbenv_ruby_version }}"
  when: rbenv_check_install|failed

- name: Check if version is the default ruby version
  become: yes
  become_user: "{{ rbenv_user }}"
  shell: ". ~/.profile && rbenv version | grep {{ rbenv_ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: yes

- name: Set default ruby version
  become: yes
  become_user: "{{ rbenv_user }}"
  shell: ". ~/.profile && rbenv global {{ rbenv_ruby_version }}"
  when: rbenv_check_default|failed

- name: install bundler
  become: yes
  become_user: "{{ rbenv_user }}"
  shell: ". ~/.profile && gem install bundler"
  args:
    creates: "/home/{{ rbenv_user }}/.rbenv/shims/bundle"
