---
- name: create isucon user
  user: name=isucon groups=www-data createhome=yes shell=/bin/bash

- name: allow isucon user to use sudo
  lineinfile: dest=/etc/sudoers.d/isucon create=yes line="isucon ALL=(ALL) NOPASSWD:ALL"

- name: set authorized_keys
  authorized_key: user=isucon key="https://github.com/{{ item }}.keys"
  with_items: "{{ key_github_users }}"

- name: create directory for portal app
  file: path="/var/www" state="directory" owner=root group=www-data mode=0775
