---
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - apt: autoclean=yes
    - apt: update_cache=yes
    - apt: upgrade=dist
    - apt: name=build-essential state=present
    - apt: name=git state=present
    - apt: name=gcc state=present
    - apt: name=patch state=present
    - apt: name=autoconf state=present
    - apt: name=automake state=present
    - apt: name=bison state=present
    - apt: name=libssl-dev state=present
    - apt: name=libyaml-dev state=present
    - apt: name=libreadline6-dev state=present
    - apt: name=zlib1g-dev state=present
    - apt: name=libncurses5-dev state=present
    - apt: name=libffi-dev state=present
    - apt: name=libgdbm6 state=present
    - apt: name=libgdbm-dev state=present
    - apt: name=libmysqlclient-dev state=present
    - apt: name=libpq-dev state=present
    - apt: name=libcurl4-openssl-dev state=present
    - apt: name=libpng16-16
    - apt: name=libpng-dev state=present
    - apt: name=libmcrypt4 state=present
    - apt: name=libmcrypt-dev state=present
    - apt: name=libtidy5deb1 state=present
    - apt: name=libtidy-dev state=present
    - apt: name=libxml2-dev state=present
    - apt: name=libxslt1-dev state=present
    - apt: name=readline-common state=present
    # for node-install
    - apt: name=curl state=present
    # for php --with-openssl
    - apt: name=pkg-config
    - apt: name=acl
