---
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - apt: name=mysql-server
    - apt: name=memcached
    - apt: name=python3-pymysql
    - name: create mysql user
      mysql_user:
        login_user: root
        name: isuconp
        password: isuconp
        priv: '*.*:ALL'
        check_implicit_admin: yes
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
