---
- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 3.1.2 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # node
    - command: /home/isucon/.xbuild/node-install v4.4.3 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
      tags:
        - nodejs
    # golang
    - shell: /home/isucon/.xbuild/go-install 1.18.3 /home/isucon/.local/go $(uname -s | tr [A-Z] [a-z]) $(dpkg --print-architecture)
      args:
        creates: /home/isucon/.local/go/bin/go

- hosts: guests:extras
  become: yes
  gather_facts: yes
  tasks:
    - name: Apt update
      apt: update_cache=yes
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
      tags: php7
    - name: PHP7 install
      apt: name="{{item}}"
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
      with_items:
        - php7.4-cli
        - php7.4-fpm
        - php7.4-mysql
        - php-memcached
      tags: php7
    - name: copy www.conf (php-fpm)
      copy: src=../files/etc/php/7.4/fpm/pool.d/www.conf dest=/etc/php/7.4/fpm/pool.d/www.conf owner=root mode=644
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
      tags: php7
    - name: stop php-fpm
      service: name=php7.4-fpm state=stopped enabled=no
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
      tags: php7

- hosts: guests:extras
  become: yes
  gather_facts: yes
  tasks:
    - name: Apt update
      apt: update_cache=yes
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      tags: php8
    - name: PHP8 install
      apt: name="{{item}}"
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      with_items:
        - php8.1-cli
        - php8.1-fpm
        - php8.1-mysql
        - php-memcached
      tags: php8
    - name: copy www.conf (php-fpm)
      copy: src=../files/etc/php/8.1/fpm/pool.d/www.conf dest=/etc/php/8.1/fpm/pool.d/www.conf owner=root mode=644
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      tags: php8
    - name: stop php-fpm
      service: name=php8.1-fpm state=stopped enabled=no
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      tags: php8
