- hosts: guests:extras
#- hosts: extras
  become: yes
  gather_facts: yes
  tasks:
    - name: create mysqldump
      get_url: url=https://github.com/catatsuy/private-isu/releases/download/img/dump.sql.bz2 dest=/home/isucon/backup/mysqldump.sql.bz2 force=1
    - name: set temporary password
      become: yes
      become_user: root
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      blockinfile:
        create: yes
        dest: &myCnf /root/.my.cnf
        content: |
          [client]
          user = root
          password = root
    - name: create database
      shell: bzcat /home/isucon/backup/mysqldump.sql.bz2 | mysql -u root
    - name: remove temporary file
      become: yes
      become_user: root
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      file:
        path: *myCnf
        state: absent
