- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: bundle install
      shell: cd /home/isucon/private_isu/webapp/ruby; bash -lc "bundle install"

- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: go build
      shell: cd /home/isucon/private_isu/webapp/golang; bash -lc "./setup.sh"

- hosts: guests:extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: download composer.phar
      get_url: url=https://getcomposer.org/composer.phar dest=/home/isucon/private_isu/webapp/php/composer.phar force=1 mode=755
    - name: composer install
      shell: cd /home/isucon/private_isu/webapp/php; bash -lc "./composer.phar install"

- hosts: guests:extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: npm install
      shell: cd /home/isucon/private_isu/webapp/node; bash -lc "npm install"
  tags:
    - nodejs

- hosts: guests:extras
  become: yes
  gather_facts: yes
  tasks:
    - copy: src=../files/home/isucon/env.sh dest=/home/isucon/env.sh owner=isucon mode=644
    - name: ruby (systemd)
      copy: src=../files/etc/systemd/system/isu-ruby.service dest=/etc/systemd/system/isu-ruby.service owner=root mode=644
    - name: go app (systemd)
      copy: src=../files/etc/systemd/system/isu-go.service dest=/etc/systemd/system/isu-go.service owner=root mode=644
    - name: node app (systemd)
      copy: src=../files/etc/systemd/system/isu-node.service dest=/etc/systemd/system/isu-node.service owner=root mode=644
      tags:
        - nodejs
    - name: php app (systemd)
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
      lineinfile:
        path: /lib/systemd/system/php7.4-fpm.service
        line: 'EnvironmentFile=/home/isucon/env.sh'
        insertafter: 'ExecReload=.*'
    - name: php app (systemd)
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
      lineinfile:
        path: /lib/systemd/system/php8.1-fpm.service
        line: 'EnvironmentFile=/home/isucon/env.sh'
        insertafter: 'ExecReload=.*'
    - name: reload daemon config
      shell: systemctl daemon-reload
    - name: default application selection
      service: name=isu-ruby state=started enabled=true
